version: "3"
services: 
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes: 
      - ./:/app:ro
      - /app/node_modules
    environment: 
      - NODE_ENV=development
      # - MONGO_USER=mugen
      # - MONGO_PASSWORD=!Mu93n
      # - MONGO_IP=mongo
      # - MONGO_PORT=27017
    command: npm run dev
  